model_list:
  - model_name: Qwen/Qwen2.5-14B-Instruct-AWQ
    litellm_params:
      model: openrouter/deepseek/deepseek-v4-flash
      api_key: os.environ/OPENROUTER_INFRA_APP_KEY
      timeout: 60
      stream: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
  set_verbose: false

router_settings:
  routing_strategy: simple-shuffle
