#!/usr/bin/env bash
# shellcheck shell=bash
# =============================================================================
# scripts/semgrep_update_rules.sh
#
# Downloads the full Semgrep community rule library to .semgrep/registry/
# so the VS Code LSP and `make semgrep` run entirely offline (no network
# timeouts, instant startup, deterministic results).
#
# Usage:
#   ./scripts/semgrep_update_rules.sh          # auto-reads token from ~/.semgrep
#   SEMGREP_APP_TOKEN=<token> ./scripts/semgrep_update_rules.sh
#
# Schedule: run periodically to pick up new rules:
#   0 6 * * 1  root  /opt/stacks/internalcmdb/scripts/semgrep_update_rules.sh
# =============================================================================
set -euo pipefail

REGISTRY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.semgrep/registry"
SEMGREP_API="https://semgrep.dev/c/p"

# ---------------------------------------------------------------------------
# Auth token — prefer env var, then fall back to ~/.semgrep/settings.yml
# ---------------------------------------------------------------------------
if [[ -z "${SEMGREP_APP_TOKEN:-}" ]]; then
    SEMGREP_APP_TOKEN=$(grep "api_token" ~/.semgrep/settings.yml 2>/dev/null | awk '{print $2}' || true)
fi

if [[ -z "${SEMGREP_APP_TOKEN:-}" ]]; then
    echo "ERROR: No SEMGREP_APP_TOKEN found. Run 'semgrep login' first." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Rule packs to download
# Each entry: <pack-slug>:<output-filename>
# ---------------------------------------------------------------------------
declare -a PACKS=(
    # Universal / default
    "default"
    "cwe-top-25"
    "r2c-security-audit"
    "r2c-ci"
    "r2c-best-practices"
    "r2c-bug-scan"
    "findsecbugs"
    "security-audit"
    "ci"

    # OWASP / Web security
    "owasp-top-ten"
    "xss"
    "sql-injection"
    "insecure-transport"
    "command-injection"
    "headless-browser"
    "secrets"
    "gitleaks"
    "supply-chain"
    "semgrep-rule-lints"
    "semgrep-misconfigurations"

    # Python ecosystem
    "python"
    "flask"
    "django"
    "fastapi"
    "jwt"
    "bandit"
    "gitlab-bandit"

    # TypeScript / JavaScript / Frontend
    "typescript"
    "javascript"
    "react"
    "nextjs"
    "nodejs"
    "expressjs"

    # Infrastructure / Config
    "dockerfile"
    "docker-compose"
    "github-actions"
    "terraform"
    "kubernetes"

    # Other languages
    "java"
    "rust"
    "ruby"
    "php"
    "kotlin"
    "scala"
    "swift"
    "c"
    "csharp"
    "elixir"
    "trailofbits"
    "phpcs-security-audit"
)

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
download_pack() {
    local slug="$1"
    local filename="$2"
    local url="${SEMGREP_API}/${slug}"
    local dest="${REGISTRY_DIR}/${filename}"
    local tmp="${dest}.tmp"

    echo -n "  Downloading p/${slug} ... "
    if curl -sf \
            --max-time 30 \
            -H "Authorization: Bearer ${SEMGREP_APP_TOKEN}" \
            -H "Accept: application/yaml" \
            "${url}" \
            -o "${tmp}" 2>/dev/null; then
        # Validate it starts with 'rules:' — some packs return JSON errors
        if head -1 "${tmp}" | grep -q "^rules:"; then
            mv "${tmp}" "${dest}"
            local count
            count=$(grep -c "^- id:" "${dest}" 2>/dev/null || echo "?")
            echo "OK (${count} rules)"
        else
            rm -f "${tmp}"
            echo "SKIP (not a valid ruleset — pack may not exist or require Pro)"
        fi
    else
        rm -f "${tmp}"
        echo "SKIP (HTTP error or timeout)"
    fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
echo "=== Semgrep Rule Library Update ==="
echo "Target: ${REGISTRY_DIR}"
echo "Date:   $(date -u '+%Y-%m-%d %H:%M UTC')"
echo ""

mkdir -p "${REGISTRY_DIR}"

# Write a metadata header so we know when rules were last refreshed
cat > "${REGISTRY_DIR}/_meta.yml" <<YAML
# DO NOT EDIT — generated by scripts/semgrep_update_rules.sh
# Last updated: $(date -u '+%Y-%m-%d %H:%M UTC')
# Semgrep version: $(/opt/semgrep-venv/bin/semgrep --version 2>/dev/null || echo unknown)
rules: []
YAML

failed=0
downloaded=0

for slug in "${PACKS[@]}"; do
    filename="${slug}.yml"
    download_pack "${slug}" "${filename}" && ((downloaded++)) || ((failed++)) || true
done

echo ""
echo "=== Summary ==="
echo "  Packs attempted: ${#PACKS[@]}"
echo "  Downloaded:      ${downloaded}"
echo "  Skipped/Failed:  ${failed}"
echo ""

# Count total rules across all downloaded packs.
# grep -c prints one count per file; awk sums them.
# 'END {print s+0}' ensures 0 is printed when no yml files exist yet.
total_rules=$(grep -hc "^- id:" "${REGISTRY_DIR}"/*.yml 2>/dev/null | awk '{s+=$1} END {print s+0}' || echo 0)
echo "  Total rules in library: ${total_rules}"
echo ""

# Validate all rules
echo "=== Validating local library ==="
/opt/semgrep-venv/bin/semgrep scan \
    --validate \
    --config /opt/stacks/internalcmdb/.semgrep/ \
    --metrics=off \
    2>&1 | tail -3

echo ""
echo "Done. VS Code → Command Palette → 'Semgrep: Restart Language Server'"
